/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.sys.webglobe;

public final class R {
  public static final class color {
    public static final int colorAccent=0x7f010000;
    public static final int colorControlHighlight=0x7f010001;
    public static final int colorControlNormal=0x7f010002;
    public static final int colorPrimary=0x7f010003;
    public static final int colorPrimaryDark=0x7f010004;
  }
  public static final class drawable {
    public static final int app_icon=0x7f020000;
    public static final int default_image=0x7f020001;
    public static final int search=0x7f020002;
  }
  public static final class id {
    public static final int GoBack=0x7f030000;
    public static final int GoForward=0x7f030001;
    public static final int Main_WebView=0x7f030002;
    public static final int SearchButton=0x7f030003;
    public static final int SettingsButton=0x7f030004;
    public static final int URLTextbox=0x7f030005;
    public static final int linear1=0x7f030006;
    public static final int linear4=0x7f030007;
    public static final int linear7=0x7f030008;
  }
  public static final class layout {
    public static final int main=0x7f040000;
    public static final int settings=0x7f040001;
  }
  public static final class string {
    public static final int app_name=0x7f050000;
  }
  public static final class style {
    public static final int AppTheme=0x7f060000;
    public static final int FullScreen=0x7f060001;
    public static final int NoActionBar=0x7f060002;
    public static final int NoStatusBar=0x7f060003;
  }
}